FROM ubuntu:lunar

WORKDIR /workspaces/darduino/

RUN apt-get update \
    && apt-get --no-install-recommends -y install \
    curl \
    git gnupg2 ca-certificates \
    gcc g++ make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists

RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/bin sh
RUN arduino-cli core install arduino:avr
